import type { SoundPreset } from "@/lib/audio/engine";

export type RipleyPreset = {
  key: string;
  chapterIndex: number;
  principleId: number;
  intensity: number;
  clarity: number;
  shift: number;
  lineOpacityScale: number;
  lineRadiusScale: number;
  particleScale: number;
  particleBrightness: number;
  veilIntensity: number;
  postBoost: number;
  cameraPosition: [number, number, number];
  cameraTarget: [number, number, number];
  soundPreset: SoundPreset;
};

export const ripleyPresets: Record<string, RipleyPreset> = {
  "prima-materia": {
    key: "prima-materia",
    chapterIndex: 0,
    principleId: 1,
    intensity: 0.42,
    clarity: 0.42,
    shift: 0.25,
    lineOpacityScale: 0.55,
    lineRadiusScale: 0.8,
    particleScale: 1.2,
    particleBrightness: 0.75,
    veilIntensity: 1.2,
    postBoost: 0.0,
    cameraPosition: [0.1, 0.1, 7.4],
    cameraTarget: [0, 0, 0],
    soundPreset: "aether-drone",
  },
  solve: {
    key: "solve",
    chapterIndex: 2,
    principleId: 3,
    intensity: 0.58,
    clarity: 0.36,
    shift: 0.4,
    lineOpacityScale: 0.35,
    lineRadiusScale: 0.7,
    particleScale: 1.35,
    particleBrightness: 0.85,
    veilIntensity: 1.25,
    postBoost: 0.05,
    cameraPosition: [-0.2, 0.2, 6.9],
    cameraTarget: [0.1, 0, 0],
    soundPreset: "mercury-glass",
  },
  separation: {
    key: "separation",
    chapterIndex: 1,
    principleId: 2,
    intensity: 0.5,
    clarity: 0.55,
    shift: 0.45,
    lineOpacityScale: 0.6,
    lineRadiusScale: 0.85,
    particleScale: 1.1,
    particleBrightness: 0.8,
    veilIntensity: 1.0,
    postBoost: 0.03,
    cameraPosition: [0.3, -0.15, 6.6],
    cameraTarget: [0, 0, 0],
    soundPreset: "cathedral",
  },
  nigredo: {
    key: "nigredo",
    chapterIndex: 4,
    principleId: 5,
    intensity: 0.36,
    clarity: 0.32,
    shift: 0.3,
    lineOpacityScale: 0.5,
    lineRadiusScale: 0.75,
    particleScale: 1.25,
    particleBrightness: 0.7,
    veilIntensity: 1.3,
    postBoost: 0.0,
    cameraPosition: [-0.1, -0.3, 7.2],
    cameraTarget: [0, 0, 0],
    soundPreset: "saturn-deep",
  },
  albedo: {
    key: "albedo",
    chapterIndex: 1,
    principleId: 2,
    intensity: 0.5,
    clarity: 0.68,
    shift: 0.52,
    lineOpacityScale: 0.7,
    lineRadiusScale: 0.9,
    particleScale: 1.05,
    particleBrightness: 0.9,
    veilIntensity: 0.85,
    postBoost: 0.02,
    cameraPosition: [0.2, 0.15, 6.4],
    cameraTarget: [0, 0, 0],
    soundPreset: "cathedral",
  },
  conjunction: {
    key: "conjunction",
    chapterIndex: 3,
    principleId: 4,
    intensity: 0.62,
    clarity: 0.52,
    shift: 0.6,
    lineOpacityScale: 0.7,
    lineRadiusScale: 0.95,
    particleScale: 1.15,
    particleBrightness: 0.9,
    veilIntensity: 0.95,
    postBoost: 0.04,
    cameraPosition: [0.5, 0.1, 6.8],
    cameraTarget: [0, 0, 0],
    soundPreset: "lunar-pulse",
  },
  fermentation: {
    key: "fermentation",
    chapterIndex: 6,
    principleId: 7,
    intensity: 0.55,
    clarity: 0.55,
    shift: 0.58,
    lineOpacityScale: 0.75,
    lineRadiusScale: 1.0,
    particleScale: 1.1,
    particleBrightness: 0.9,
    veilIntensity: 0.9,
    postBoost: 0.05,
    cameraPosition: [0.2, 0.25, 6.6],
    cameraTarget: [0, 0, 0],
    soundPreset: "lunar-pulse",
  },
  distillation: {
    key: "distillation",
    chapterIndex: 2,
    principleId: 3,
    intensity: 0.6,
    clarity: 0.6,
    shift: 0.65,
    lineOpacityScale: 0.75,
    lineRadiusScale: 0.9,
    particleScale: 1.2,
    particleBrightness: 0.95,
    veilIntensity: 0.9,
    postBoost: 0.06,
    cameraPosition: [-0.15, 0.35, 6.4],
    cameraTarget: [0, 0.05, 0],
    soundPreset: "mercury-glass",
  },
  citrinitas: {
    key: "citrinitas",
    chapterIndex: 0,
    principleId: 1,
    intensity: 0.62,
    clarity: 0.7,
    shift: 0.72,
    lineOpacityScale: 0.85,
    lineRadiusScale: 1.05,
    particleScale: 1.05,
    particleBrightness: 1.05,
    veilIntensity: 0.75,
    postBoost: 0.08,
    cameraPosition: [0.15, -0.2, 6.2],
    cameraTarget: [0, 0, 0],
    soundPreset: "cathedral",
  },
  coagula: {
    key: "coagula",
    chapterIndex: 4,
    principleId: 6,
    intensity: 0.68,
    clarity: 0.75,
    shift: 0.8,
    lineOpacityScale: 1.0,
    lineRadiusScale: 1.15,
    particleScale: 0.95,
    particleBrightness: 0.9,
    veilIntensity: 0.7,
    postBoost: 0.06,
    cameraPosition: [-0.2, -0.1, 6.0],
    cameraTarget: [0, 0, 0],
    soundPreset: "saturn-deep",
  },
  rubedo: {
    key: "rubedo",
    chapterIndex: 5,
    principleId: 7,
    intensity: 0.72,
    clarity: 0.78,
    shift: 0.9,
    lineOpacityScale: 1.05,
    lineRadiusScale: 1.1,
    particleScale: 1.0,
    particleBrightness: 1.1,
    veilIntensity: 0.7,
    postBoost: 0.12,
    cameraPosition: [0.1, 0.2, 6.1],
    cameraTarget: [0, 0, 0],
    soundPreset: "cathedral",
  },
};

export function getRipleyPreset(key: string) {
  return ripleyPresets[key] ?? ripleyPresets["prima-materia"];
}
